### ISSUE TITLE
Touch-dimmer change in procedure

### ISSUE THREAD

**Issue by cschmidiger** [Twistx77/Gemma-FW#10]
**Problem**
The touch-dimming currently has the logic that it toggles the direction. First touch it goes up, second touch it goes down. I think this is not good. I would like to try out something perhaps more intuitive and practival.

**Solution**
Whenever the global brigthenss level is <50% then increase the brightness steadily. When the global brightness level is >= 50% then decrease the brightness level steadily. This shall apply to all sensors main, and night-lights.

**Comment by Twistx77** [comment]
Done

**Comment by cschmidiger** [comment]
It seems to work -> how do you like it? Do you think it's intuitive? A follow-up question I'd have: can the 50% be reduced to another number? I guess the visibly noticable middle between dark and bright is probably at 30-40%. Not super important for now but a cosmetic and a fine-tuning.

**Comment by Twistx77** [comment]
Can be easily changed but I think we need to check gamma correction. Our eyes don't have a linear response of the light seen, that is why you don't see much change between 50 and 100. So the correct approach would be for me to do gamma correction

**Comment by cschmidiger** [comment]
I agree and this pretty much sounds like the crazy VOLPI stuff. So are you going to look at the Gamma correction? I'm glad you are an expert 😊

**Comment by Twistx77** [comment]
Closed. The Gamma correction is another topic
