### ISSUE TITLE
Number of LED max.

### ISSUE THREAD

**Issue by cschmidiger** [Twistx77/Gemma-FW#11]
I have the impression that the max. number of LED is limited to a number somewhere around 140...? Can we discard this limit as to not restrict ourselves? According to the documentation the UUID: 2f7980c8-28d0-4c1c-ad2c-78036e8faf10 allows values between 0-255. Don't think this is true, please advise.

**Comment by Twistx77** [comment]
Now you can go to 255. Going higher would require some testing. Keep in mind that the more the LEDs you have the more data is transmitter to the LED strip and therefor it takes longer to do everything. For now it is not noticeable for the lengths that we are using but it will definitely will be noticeable if we go higher in number of LEDs.

**Comment by Twistx77** [comment]
Done to the extent possible at the moment. If we need to use more LEDs we can open a new issue,
