### ISSUE TITLE
Dimming speed (touch-dimming)

### ISSUE THREAD

**Issue by cschmidiger** [Twistx77/Gemma-FW#14]
**Touch-dimming**
Don't want to freak you out but could it be possible to set the dimming speed as a UUID? I like it as is but almost a little bit too slow. Having a UUID would allow to adjust and also during the testing activities. These are the things that a user will feel every time when using the lamp so I believe it's worth giving the possibility to fine-tune.

**Comment by Twistx77** [comment]
I can but there are limits on how fast it can be done if we want to keep 100% of the brightness steps.

**Comment by Twistx77** [comment]
Do you think this would need to be user adjustable? Otherwise I propose to spend some time test it and decide on a fixed value.
